=== sevenfold-IS2011/zoo/xml/warehouse.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.zoo.com"
    elementFormDefault="qualified">

<xs:element name="zoo" type="Tzoo"/>

<xs:complexType type="Tzoo">
    <xs:sequence>
        <xs:element name="magazzino" type="Tmagazzino" />
    </xs:sequence>
</xs:complexType>

<xs:complexType type="Tmagazzino">
    <xs:sequence>
        <xs:element name="cibo" type="Tcibo"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
    <xs:attribute name="nome" type="xs:integer" use="required"/>
</xs:complexType>

<xs:complexType type="Tcibo">
    <xs:sequence>
        <xs:element name="area" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

</xs:schema>

=== sevenfold-IS2011/zoo/xml/warehouse.xml
<magazzino xmlns="http://www.zoo.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.zoo.com warehouse.xsd">
<cibo nome="carne" quantita="44" id="4"><area>4</area><area>6</area></cibo><cibo nome="foglie" quantita="55" id="5"><area>2</area></cibo><cibo nome="arbusti" quantita="22" id="2"><area>3</area></cibo><cibo nome="banane" quantita="15" id="1"><area>1</area></cibo><cibo nome="erba" quantita="67" id="3"><area>5</area></cibo></magazzino>
