=== sevenfold-IS2011/zoo/xml/worker.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:zoo="http://www.zoo.com"
    targetNamespace="http://www.zoo.com"
    elementFormDefault="qualified">

<xs:element name="workers" type="zoo:Tworkers"/>

<xs:complexType name="Tworkers">
    <xs:sequence  maxOccurs="unbounded">
        <xs:element name="impiegato" type ="zoo:Timpiegato" minOccurs="0" />
        <xs:element name="manager" type ="zoo:Tmanager" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Timpiegato">
    <xs:sequence>
        <xs:element name="username" type ="xs:string"/>
        <xs:element name="password" type ="xs:string"/>
        <xs:element name="nome" type ="xs:string"/>
        <xs:element name="sesso" type ="zoo:Tsesso"/>
        <xs:element name="eta" type="zoo:Teta"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Tmanager">
    <xs:sequence>
        <xs:element name="username" type ="xs:string"/>
        <xs:element name="password" type ="xs:string"/>
        <xs:element name="nome" type ="xs:string"/>
        <xs:element name="sesso" type ="zoo:Tsesso"/>
        <xs:element name="eta" type="zoo:Teta"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="Tsesso">
    <xs:restriction base="xs:string">
        <xs:enumeration value="F"/>
        <xs:enumeration value="M"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="Teta">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== sevenfold-IS2011/zoo/xml/workers.xml
<workers xmlns="http://www.zoo.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.zoo.com worker.xsd">
    <impiegato>
        <username>mario</username>
        <password>k8n3IKklUMu2fg</password>
        <nome>Mario</nome>
        <sesso>F</sesso>
        <eta>23</eta>
    </impiegato>

    <impiegato>
        <username>maria</username>
        <password>M8x2IK5lJMu9k1</password>
        <nome>Maria</nome>
        <sesso>F</sesso>
        <eta>51</eta>
    </impiegato>

    <impiegato>
        <username>mirco</username>
        <password>b8x2kI6lJMg3kh</password>
        <nome>Mirco</nome>
        <sesso>F</sesso>
        <eta>27</eta>
    </impiegato>

    <impiegato>
        <username>martina</username>
        <password>bzx2kP3lJIg3nh</password>
        <nome>Martina</nome>
        <sesso>M</sesso>
        <eta>26</eta>
    </impiegato>

    <manager>
        <username>marco</username>
        <password>mzx2kP3qJDg3kg</password>
        <nome>Marco</nome>
        <sesso>M</sesso>
        <eta>25</eta>
    </manager>

    <manager>
        <username>giovanna</username>
        <password>zxVcGz0BPdHkY</password>
        <nome>Giovanna</nome>
        <sesso>F</sesso>
        <eta>24</eta>
    </manager>

		<manager>
			<username>lucanervi</username>
			<password>zxePlNSDQjsxg</password>
			<nome>Luca Nervi</nome>
			<sesso>M</sesso>
			<eta>23</eta>
		</manager>


		<impiegato>
			<username>paolobitta</username>
			<password>zx2kL4qmDw3kg</password>
			<nome>Paolo Bitta</nome>
			<sesso>M</sesso>
			<eta>35</eta>
		</impiegato>
		
	<manager>
		<username>ombretta</username>
		<password>zxFSwnannEpRc</password>
		<nome>Ombretta</nome>
		<sesso>F</sesso>
		<eta>35</eta>
	</manager>
<impiegato><username>ogaggi</username><password>zxPmex6//Xpx6</password><nome>Gaggi</nome><sesso>F</sesso><eta>35</eta></impiegato></workers>
